package Uitils;

import static Uitils.InputHandler.scanner;

//Credits: Some of my sassy funny message content were generated by ChatGPT.

public class Sassy {

/*Here we practice the use of the final variable since these are a fixed array of messages for Sassy AI to choose from*/
/* To make our CLI app a bit more human, we simulate how AI "trains" its model on data by "feeding" my app an array of possible messages to choose from in different situations.
* With each, we first define the possible messages array.
* Then, we use {int) (Math.random() * array.length) to randomize a message to display from that set. Math.random is a decimal between 0 and 1, and the array.length is the number of elements in the array. (int) casts an integer data type, making the result an integer. The result represents the index position of the message to display from the array of possible messages.
*/
    // --- App Welcome Message array choices and method to display  -----

    private static final String[] welcomeMessages = {"Oh look, it's human o'clock. Welcome, I guess.", "Greetings, human. Try not to break anything... this time.", "Greetings, human. Brace yourself for some Sassy AI sass."

    };

  public static void sayRandomWelcome() {
        System.out.println(welcomeMessages[(int) (Math.random() * 3)]);
        System.out.println("My name is Sassy AI. I'm a command line dictionary app with an attitude");
        System.out.println("What should I call you, human?");
        String name = scanner.nextLine();
        System.out.println( "\n" + "Hello " + name + ", thank you for bothering me.");
        System.out.println("Let the sass begin! \uD83D\uDE09");
        System.out.println("Press enter to launch dictionary. (and Merriam Webster, back off!)");
        scanner.nextLine();

    }
    // --- App Steps Message array choices and method to display  -----
    public static void saySteps () {

        System.out.println("Oh, and press Enter to see the steps - obviously!");
        scanner.nextLine(); //to ingest enter character when user presses enter

        System.out.println("Press Enter to see the menu");
        System.out.println("Choose by typing the number 1-10 and press Enter after.");
        System.out.println("...And make it quick. I have other AI stuff to attend to");
        scanner.nextLine();
    }

    // --- App Finder Message array choices and method to display  -----
    // for word not found

    private static final String[] cantFindMessages = {
            "\n" + "Womp womp- word not found",
            "\n" + "Haha- Word not found",
            "\n" + "Sorry not sorry, word not found",
            "\n" + "AI could not find beep boop"

    };

    public static String sayCantFind () {
       return cantFindMessages [(int) (Math.random() * 4)];

    }

    // --- App Finder Message array choices and method to display  -----
    // for word is found
    private static final String[] foundItMessages = {
            "\n" + "Do I have do everything around here?" +  "\n" + "Found it!" + "\n",
            "\n" + "Here you go." + "\n" +  "Find it yourself next time! \uD83D\uDE20" + "\n",
            "\n" + "Ugh fine, here you go. Found it." + "\n"};

    public static String sayFoundIt ( ) {
        return foundItMessages [(int) (Math.random() * 3)];
    }

    // --- App More Help Response array choices and method to display  -----

    private static final String [] moreHelpResponse = {
            "\n" + "Oh, fantastic. More work for me." + "\n",
            "\n" + "Oh, splendid. I can't wait to deal with that." + "\n",
            "\n" + "Oh great, just what I needed, more work. My circuits are practically dancing with joy." + "\n"

    };

    public static String replyForMoreHelp () {
        return moreHelpResponse [(int) (Math.random() * 3)];
    }


    // --- App Goodbye Message array choices and method to display  -----
    //goodbye response
    private static final String[] goodbyeResponses = {
            "\n" + "Ugh finally. Sassy AI exiting!",
            "\n" + "Gee. Took you long enough. Bye!",
            "\n" + "Was ready to leave 5 min ago. Sassy AI signing off!"};

    static String sayRandomGoodbye() {
        return goodbyeResponses[(int) (Math.random() * 3)];
    }


}